=== xaraya/core/tests/modwizard/modwizard.dtd
<!-- ========================================================================

    XARAYA MODULE WIZARD - DTD

-->

<!-- the root element -->
<!ELEMENT xaraya_module (
    about
    ,registry
    ,configuration
    ,database
    ,blocks
    )>

<!--

    ABOUT SECTION

-->
<!ELEMENT about ( name, copyright, license, author, description )>
<!ELEMENT name ( #PCDATA )>
<!ELEMENT copyright ( #PCDATA )>
<!ELEMENT license   ( #PCDATA )>
<!ELEMENT author    ( name, email )>
<!ELEMENT email    ( #PCDATA )>
<!ELEMENT category    ( #PCDATA )>
<!ELEMENT class    ( #PCDATA )>

<!ELEMENT description ( short, long, category, class )>
    <!ELEMENT short ( #PCDATA )>
    <!ELEMENT long ( #PCDATA )>

<!--

    XARAYA.ORG REGISTRY SECTION

-->
<!ELEMENT registry ( id | name )* >
<!ELEMENT id ( #PCDATA )>

<!--

    DATABASE SECTION
    ================

    Is not necessary to fill something in here.

-->
<!ELEMENT database ( table )* >

<!ELEMENT table ( label, labelfields, structure, order?, index* )* >
<!ATTLIST table
    name        CDATA #REQUIRED
    itemtype    CDATA #REQUIRED
    admin       ( true | false ) 'true'
    user        ( true | false ) 'true'
    >

<!ELEMENT label ( #PCDATA )>
<!ELEMENT labelfields    ( field+ )>
<!ATTLIST labelfields
     separator  CDATA '|' >
<!ELEMENT order ( field+ )>

<!ELEMENT structure ( field )*>

<!ELEMENT field ( dd_type?, dd_validation?, label? )>
<!--

    type   => from xarDB

-->
<!ATTLIST field
     name        CDATA #REQUIRED
     type        ( integer | char | varchar | text | blob | boolean | datetime | date | float | timestamp ) #IMPLIED
     size        CDATA #IMPLIED
     notnull     ( true | false ) 'false'
     primary_key ( true | false ) 'false'
     width       CDATA #IMPLIED
     decimals    CDATA #IMPLIED
     default     CDATA #IMPLIED
     increment   ( true | false ) 'false'
     overview    ( true | false ) 'true'
     unsigned    ( true | false ) 'false'
     transform   ( true | false ) 'false' >

<!ELEMENT dd_type       ( #PCDATA )>
<!ELEMENT dd_validation ( #PCDATA )>

    <!ELEMENT index ( comment?, field+ )>
    <!ATTLIST index
        name    CDATA #REQUIRED
        unique  ( true |  false ) "true" >

    <!ELEMENT comment ( #PCDATA ) >

<!--

    CONFIGURATION SECTION

-->
<!ELEMENT configuration ( dependency?, capabilities, modvars, hooks, security )>

<!ELEMENT capabilities ( supportshorturls, setpagetitle, item_hooks, module_hooks, search_hook, transform_hooks, user_menu_hook, waiting_content_hook )* >
<!ELEMENT supportshorturls ( #PCDATA )>
<!ELEMENT dependency ( #PCDATA )>
<!ELEMENT setpagetitle ( #PCDATA )>
<!ELEMENT item_hooks ( #PCDATA )>
<!ELEMENT transform_hooks ( #PCDATA )>
<!ELEMENT user_menu_hook ( #PCDATA )>
<!ELEMENT waiting_content_hook ( #PCDATA )>
<!ELEMENT module_hooks ( #PCDATA )>
<!ELEMENT search_hook ( #PCDATA )>

<!ELEMENT modvars ( var )*>

<!ELEMENT var ( #PCDATA )>
<!ATTLIST var
    type CDATA  #REQUIRED
    name CDATA  #REQUIRED >


<!ELEMENT hooks ( hook )* >

<!ELEMENT hook EMPTY>
<!ATTLIST hook
    module      CDATA #REQUIRED
    >

<!ELEMENT security ( component )*>
<!ELEMENT component ( query+, mask+ )+>
<!ATTLIST component
    name CDATA #REQUIRED >

<!ELEMENT query ( header, select, limit? )>
<!ELEMENT header ( #PCDATA )>
<!ELEMENT select ( #PCDATA )>
<!ELEMENT limit ( #PCDATA )>

<!ELEMENT mask (  instance, level, comment )>
<!ATTLIST mask
    name CDATA #REQUIRED >
<!ELEMENT instance ( #PCDATA )>
<!ELEMENT level ( #PCDATA )>


<!ELEMENT blocks ( block* )>
<!ELEMENT block ( #PCDATA ) >
<!ATTLIST block
    name CDATA #REQUIRED >

=== xaraya/core/tests/modwizard/minimal.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- vim: tw=0
-->
<!DOCTYPE xaraya_module SYSTEM "./modwizard.dtd">

<xaraya_module>

    <!-- ABOUT

        Information about you and your module

    -->
    <about>

        <name>ModWizard Example - Minimal </name>
        <copyright>by Michael Jansen</copyright>
        <license>GPL (http://www.gnu.org/licenses/gpl.html)</license>

        <author>
            <name>Michael Jansen</name>
            <email>module-wizard@michael-jansen.biz</email>
        </author>


        <description>

            <!-- add a short ONE LINE description -->
            <short>Module Wizard Test Module I</short>
            <!-- add a description as long and detailed as you want. -->
            <long>
            * The minimal module to generate
            *   # no tables
            *   # no hooks
            *   # no blocks
            *   </long>
        </description>

    </about>

    <!-- MODULE REGISTRY

        insert the appropriate values you got from the module registry at
        http://www.xaraya.org

    -->
    <registry>

        <id>5648880</id>
        <name>modwizard_minimal</name>

    </registry>

    <!-- MODULE CONFIGURATION related stuff -->
    <configuration>

        <!-- CAPABILITIES OF THE MODULE

        -->
        <capabilities>

            <!-- Add code for short url-support? -->
            <supportshorturls>yes</supportshorturls>

            <!-- Add code to change <head> -> <title> tag for each page? -->
            <setpagetitle>yes</setpagetitle>

            <item_hooks>no</item_hooks>
            <module_hooks>no</user_menu_hook>
            <search_hook>no</search_hook>
            <transform_hooks>no</transform_hooks>
            <user_menu_hook>no</user_menu_hook>
            <waiting_content_hook>no</waiting_content_hook>

        </capabilities>


        <!-- MODULE VARIABLES

            * create and initialize / remove in xarinit
            * create a default admin_configuration possibility ??

        -->
        <modvars>
            <!--
            <var type="number" name="MembersPerPage">0</var>
            -->
        </modvars>

        <!-- HOOKS

            You have different options here:

                The enable attribute controls the generation of the hook
                calls. These calls are only generated if you say enable="yes" !

                Inside you can list module which should be hooked during
                module initialization.

        -->
        <hooks />

        <!-- SECURITY related stuff ( ROLES / PRIVILEGES )

            Create / remove Instances and Masks during initialization / removing

                The appropriate calls have to be inserted manually

            MODULE Level Instance and Masks for Blocks and Itemtypes will be created automatically and used to
            provide basic access control.
        -->
        <security />

    </configuration>

    <!-- DATABASE related stuff -->
    <database />

    <!-- BLOCKS

        stub functions and privileges will be generated
    -->
    <blocks />

</xaraya_module>

=== xaraya/core/tests/modwizard/typical.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- vim: tw=0
-->
<!DOCTYPE xaraya_module SYSTEM "./modwizard.dtd">

<xaraya_module>

    <!-- ABOUT

        Information about you and your module

    -->
    <about>

        <name>ModWizard Example - Typical</name>
        <copyright>by Michael Jansen</copyright>
        <license>GPL (http://www.gnu.org/licenses/gpl.html)</license>

        <author>
            <name>Michael Jansen</name>
            <email>module-wizard@michael-jansen.biz</email>
        </author>


        <description>

            <!-- add a short ONE LINE description -->
            <short>Module Wizard Test Module II</short>
            <!-- add a description as long and detailed as you want. -->
            <long>
            * A typical module with tables and blocks
            *   # 2 tables
            *   # 2 blocks
            *   # uses hooks
            * </long>
        </description>

    </about>

    <!-- MODULE REGISTRY

        insert the appropriate values you got from the module registry at
        http://www.xaraya.org

    -->
    <registry>

        <id>5648882</id>
        <name>modwizard_typical</name>

    </registry>

    <!-- MODULE CONFIGURATION related stuff -->
    <configuration>

        <!-- CAPABILITIES OF THE MODULE

        -->
        <capabilities>

            <!-- Add code for short url-support? -->
            <supportshorturls>yes</supportshorturls>

            <!-- Add code to change <head> -> <title> tag for each page? -->
            <setpagetitle>yes</setpagetitle>

            <!-- Code for hooks ?

                 module hooks are generated if either transform_hooks or item_hooks are generated
            -->
            <item_hooks>no</item_hooks>
            <transform_hooks>no</transform_hooks>

        </capabilities>


        <!-- MODULE VARIABLES

            * create and initialize / remove in xarinit
            * create a default admin_configuration possibility ??

        -->
        <modvars>
            <!--
            <var type="number" name="MembersPerPage">0</var>
            -->
        </modvars>

        <!-- HOOKS

            You have different options here:

                The enable attribute controls the generation of the hook
                calls. These calls are only generated if you say enable="yes" !

                Inside you can list module which should be hooked during
                module initialization.

        -->
        <hooks enable="true">
            <hook module="hitcount"   require="yes" />
            <hook module="ratings"    require="no" />
            <hook module="comments"   require="yes" />
            <hook module="categories" require="no" />
        </hooks>

        <!-- SECURITY related stuff ( ROLES / PRIVILEGES )

            Create / remove Instances and Masks during initialization / removing

                The appropriate calls have to be inserted manually

            MODULE Level Instance and Masks for Blocks and Itemtypes will be created automatically and used to
            provide basic access control.
        -->
        <security />

    </configuration>

    <!-- DATABASE related stuff -->
    <database>

        <!-- Declare a database table.

             We will generate code for

             USER VIEW
             =========

                * show all
                * display one

             ADMIN VIEW
             ==========

                * show all ( with links to edit / delete / modify / create )
                * delete
                * modify
                * create


            @itemtype   =>  'The numeric itemtype'
            @admin      =>  create admin interface for this itemtype? ( yes )
            @user       =>  cerate user interface for this itemtype?  ( yes )

        -->
        <table name="member" itemtype="1">

            <label>Member</label>
            <labelfields separator=", "><field name="lastname" /><field name="firstname" /></labelfields>

            <!-- describe the table -->
            <structure>

                <!-- the one and only primary_key field is mapped to 'Item ID'. No need to specify ourselve -->
                <field name="memid"     type="integer" size="6"  notnull="true" primary_key="true" increment="true" overview="false">
                    <label>Id</label>
                </field>

                <!-- Default Input type is textbox. No need to specify ourselve -->
                <field name="lastname"  type="varchar" size="32" notnull="true" overview="true">
                    <label>Lastname</label>
                </field>

                <field name="firstname" type="varchar" size="32" overview="true">
                    <label>Firstname</label>
                </field>

                <field name="shortname" type="varchar" size="32" overview="true">
                    <label>Shortname</label>
                </field>

                <field name="email"     type="varchar" size="100" overview="false">
                    <dd_type>email</dd_type>
                    <label>Email</label>
                </field>

                <field name="birthday"  type="date"               overview="false">
                    <dd_type>calendar</dd_type>
                    <label>Birthday</label>
                </field>

                <field name="city"      type="varchar" size="40" overview="false">
                    <label>City</label>
                </field>

                <field name="picture"   type="varchar" size="20"  overview="false">
                    <dd_type>imagelist</dd_type>
                    <dd_validation>players/</dd_validation>
                    <label>Picture</label>
                </field>

            </structure>

            <order>
                <field name="lastname" />
                <field name="firstname" />
            </order>

            <index name="name" unique="true">
                <comment>index for name searching</comment>
                <field name="lastname" />
                <field name="firstname" />
            </index>

            <index name="birthday" unique="false">
                <comment>index for birthday access</comment>
                <field name="birthday" />
            </index>

        </table>

        <table name="events" itemtype="2">

            <label>Events</label>
            <labelfields separator=", "><field name="name" /></labelfields>

            <!-- describe the table -->
            <structure>

                <!-- the one and only primary_key field is mapped to 'Item ID'. No need to specify ourselve -->
                <field name="mid"     type="integer" size="6"  notnull="true" primary_key="true" increment="true" overview="false">
                    <label>Id</label>
                </field>

                <!-- Default Input type is textbox. No need to specify ourselve -->
                <field name="name"  type="varchar" size="32" notnull="true" overview="true">
                    <label>Name</label>
                </field>

                <field name="evt_date"  type="date"               overview="false">
                    <dd_type>calendar</dd_type>
                    <label>Date</label>
                </field>

            </structure>

            <order>
                <field name="evt_date" />
                <field name="name" />
            </order>

            <index name="evt_date" unique="false">
                <comment>index for birthday access</comment>
                <field name="evt_date" />
            </index>

        </table>

    </database>

    <!-- BLOCKS

        stub functions and privileges will be generated
    -->
    <blocks>

        <!-- declaration of a block -->
        <block name="block1" />
        <block name="block2" />

    </blocks>

</xaraya_module>
